# Template Bridge

- "configure terminal"
- "interface {{ interface_olt}}"
- "onu {{ onu_id }} type {{ jenismodem }} sn {{ sn }}"
- "exit"
- "interface {{ interface_onu }}"
- "name {{ customer.name }}"
- "description {{ customer.address }}"
- "tcont 1 name CIGNAL profile UP-{{ paket }}
- "gemport 1 name CIGNAL tcont 1"
- "exit"
- "interface vport-1/{{ pon_port }}/{{ pon_slot }}.{{ onu_id }}:1"
- "service-port 1 user-vlan {{ vlan }} vlan {{ vlan }}"
- "qos traffic-policy DOWN-{{ paket }}"
- "exit"
- "pon-onu-mng {{ interface_onu }}"
- "service CIGNAL gemport 1 vlan {{ vlan }}"
- "vlan port eth_0/1 mode tag vlan {{ vlan }}"
- "vlan port eth_0/2 mode tag vlan {{ vlan }}"
- "vlan port eth_0/3 mode tag vlan {{ vlan }}"
- "vlan port eth_0/4 mode tag vlan {{ vlan }}"
- "exit"




# interface gpon_olt-1/3/6
# onu 1 type ALL sn ZTEGC08F2BF1
# exit
# interface gpon_onu-1/3/6:1
# name Pondok Darun Najah
# description BRIDGE FIZNA
# tcont 1 name CIGNAL profile UP-50M
# gemport 1 name CIGNAL tcont 1
# exit
# interface vport-1/3/6.1:1
# service-port 1 user-vlan 513 vlan 513
# qos traffic-policy DOWN-50M direction egress
# exit
# pon-onu-mng gpon_onu-1/3/6:1
# service CIGNAL gemport 1 vlan 513
# vlan port eth_0/1 mode tag vlan 513
# vlan port eth_0/2 mode tag vlan 513
# vlan port eth_0/3 mode tag vlan 513
# vlan port eth_0/4 mode tag vlan 513